coverage:
  precision: 2
  round: down
  range: "70...100"
  status:
    project:
      default:
        target: 80%
        threshold: 2%
    patch:
      default:
        target: 80%
        # Don't fail PRs on patch coverage - some code (like terminal backends)
        # is difficult to test in CI. We rely on project coverage instead.
        informational: true

comment:
  layout: "reach,diff,flags,files"
  behavior: default
  require_changes: true
