;;; beads-command-prune.el --- Prune command class for beads -*- lexical-binding: t; -*-

;; Copyright (C) 2025

;; Author: Beads Contributors
;; Keywords: tools

;; This file is not part of GNU Emacs.

;;; Commentary:

;; This module defines the `beads-command-prune' EIEIO class for the
;; `bd prune' command.  The class includes full slot metadata for
;; automatic transient menu generation via `beads-defcommand'.
;;
;; The bd prune command permanently deletes closed non-ephemeral beads
;; (tasks, features, bugs, chores, etc.) and their associated data.
;; Requires either `--older-than' or `--pattern' as a safety gate so a
;; muscle-memory `--force' cannot wipe every closed bead.
;;
;; Deletes: issues, dependencies, labels, events, and comments for
;; matching beads.
;; Skips: pinned beads, open/in-progress beads, and ephemeral beads.
;; To delete closed ephemeral beads use `bd purge' instead.

;;; Code:

(require 'beads-command)
(require 'beads-meta)
(require 'beads-option)
(require 'transient)

;;; Prune Command

;;;###autoload (autoload 'beads-prune "beads-command-prune" nil t)
(beads-defcommand beads-command-prune (beads-command-global-options)
  ((dry-run
    :type boolean
    :group "Options"
    :level 1
    :order 1
    :documentation "Preview what would be pruned with stats")
   (force
    :type boolean
    :short-option "f"
    :group "Options"
    :level 1
    :order 2
    :documentation "Actually prune (without this, shows preview)")
   (older-than
    :type (or null string)
    :prompt "Older than (e.g. 30d, 2w, 60): "
    :group "Options"
    :level 1
    :order 3
    :documentation "Only prune beads closed more than N ago (e.g., 30d, 2w, 60)")
   (pattern
    :type (or null string)
    :prompt "ID glob pattern (e.g. 'gm-old-*' or '*'): "
    :group "Options"
    :level 1
    :order 4
    :documentation "Only prune beads matching ID glob pattern (e.g., 'gm-old-*')"))
  :documentation "Represents bd prune command.
Permanently deletes closed non-ephemeral beads and their data.
Requires --older-than or --pattern as a safety gate.")


(cl-defmethod beads-command-validate ((command beads-command-prune))
  "Validate prune COMMAND.
Enforces the safety gate: at least one of --older-than or --pattern
must be specified with a non-empty value, mirroring bd's own check.
Empty strings are rejected so an accidentally cleared transient field
does not bypass the gate."
  (or (cl-call-next-method)
      (with-slots (older-than pattern) command
        (let ((have-older-than (and older-than
                                    (not (string-empty-p older-than))))
              (have-pattern (and pattern
                                 (not (string-empty-p pattern)))))
          (unless (or have-older-than have-pattern)
            "Specify --older-than or --pattern (safety gate, prevents accidental wipe)")))))

;; Note: Transient menu `beads-prune' is auto-generated by
;; `beads-defcommand' above (default :transient t behavior).

(provide 'beads-command-prune)
;;; beads-command-prune.el ends here
