;;; beads-command-close.el --- Close command class for beads -*- lexical-binding: t; -*-

;; Copyright (C) 2025

;; Author: Beads Contributors
;; Keywords: tools

;; This file is not part of GNU Emacs.

;;; Commentary:

;; This module defines the `beads-command-close' EIEIO class for the
;; `bd close' command.  The class includes full slot metadata for
;; automatic transient menu generation via `beads-defcommand'.
;;
;; The bd close command closes one or more issues with a required
;; reason.  Closing an issue marks it as complete and records the
;; reason for closure.
;;
;; Features:
;; - Close single or multiple issues at once
;; - Required reason field for documentation
;; - Invalidates completion cache after closing
;;
;; Usage:
;;   (beads-command-execute (beads-command-close :issue-ids '("bd-1")
;;                                               :reason "Done"))
;;   (beads-execute 'beads-command-close)  ; convenience function
;;   (beads-close)           ; invoke transient menu

;;; Code:

(require 'beads)
(require 'beads-command)
(require 'beads-meta)
(require 'beads-option)
(require 'beads-types)

;;; Close Command

;;;###autoload (autoload 'beads-close "beads-command-close" nil t)
(beads-defcommand beads-command-close (beads-command-global-options)
  ((issue-ids
    :positional 1
    :type (list-of string)
    :separator " "
    :short-option "i"
    :transient transient-option
    :argument "--id="
    :prompt "Issue ID: "
    :reader beads--read-issue-at-point-or-prompt
    :group "Close Issue"
    :level 1
    :order 1
    :required t)
   (reason
    :type (or null string)
    :short-option "r"
    :transient beads-transient-multiline
    :documentation "Close Reason"
    :group "Close Issue"
    :level 1
    :order 2
    :required t)
   (claim-next
    :type boolean
    :short-option "c"
    :group "Options"
    :level 3)
   (continue-mol
    :long-option "continue"
    :type boolean
    :short-option "C"
    :group "Options"
    :level 3)
   (force
    :short-option "f"
    :type boolean
    :group "Options"
    :level 2)
   (session
    :type (or null string)
    :short-option "I"
    :group "Options"
    :level 4)
   (suggest-next
    :type boolean
    :short-option "S"
    :group "Options"
    :level 3))
  :documentation "Close one or more issues with a required reason.
  When executed with :json t, returns beads-issue instance (or list
  of instances when multiple IDs provided)."
  :result (list-of beads-issue))


;; Validate override removed: the base method checks :required slots
;; automatically via beads-command-validate-slots.

;; Parse override removed: the base method handles JSON-to-domain
;; parsing automatically via :result (list-of beads-issue).
;; The execute-interactive method normalizes results to a list.

(cl-defmethod beads-command-execute-interactive ((cmd beads-command-close))
  "Execute CMD to close issue and show result."
  (oset cmd json t)
  (let* ((result (beads-command-execute cmd))
         (issues (if (listp result) result (list result))))
    (beads--invalidate-completion-cache)
    (if issues
        (message "Closed %d issue%s: %s"
                 (length issues)
                 (if (= (length issues) 1) "" "s")
                 (mapconcat (lambda (i) (oref i id)) issues ", "))
      (message "No issues closed"))))

;; Note: Transient menu `beads-close' is auto-generated by
;; `beads-defcommand' above (default :transient t behavior).
;; The transient docstring is extracted from the first sentence
;; of :documentation.

(provide 'beads-command-close)
;;; beads-command-close.el ends here
