;;; beads-command-restore.el --- Restore command class for beads -*- lexical-binding: t; -*-

;; Copyright (C) 2025

;; Author: Beads Contributors
;; Keywords: tools

;; This file is not part of GNU Emacs.

;;; Commentary:

;; This module defines the `beads-command-restore' EIEIO class for the
;; `bd restore' command.  Restores a compacted issue from Dolt version
;; history.
;;
;; Usage:
;;   (beads-execute 'beads-command-restore :issue-id "bd-42")
;;   (beads-restore)  ; invoke transient menu

;;; Code:

(require 'beads-util)
(require 'beads-command)
(require 'beads-meta)
(require 'beads-option)

;;; Restore Command

;;;###autoload (autoload 'beads-restore "beads-command-restore" nil t)
(beads-defcommand beads-command-restore (beads-command-global-options)
  ((issue-id
    :positional 1
    :type (or null string)
    :short-option "i"
    :argument "--id="
    :prompt "Issue ID: "
    :reader beads-reader-close-issue-id
    :group "Restore"
    :level 1
    :order 1
    :required t)
   (json
    :type boolean
    :documentation "Output restore results in JSON format"
    :group "Options"
    :level 2
    :order 2))
  :documentation "Restore a compacted issue from Dolt history.
Requires Dolt backend.")


;; Validate override removed: the base method checks :required slots
;; automatically via beads-command-validate-slots.

;; Note: Transient menu `beads-restore' is auto-generated by
;; `beads-defcommand' above (default :transient t behavior).

(provide 'beads-command-restore)
;;; beads-command-restore.el ends here
