;;; beads-command-sql.el --- SQL command class for beads -*- lexical-binding: t; -*-

;; Copyright (C) 2025

;; Author: Beads Contributors
;; Keywords: tools

;; This file is not part of GNU Emacs.

;;; Commentary:

;; This module defines the `beads-command-sql' EIEIO class for the
;; `bd sql' command.  The class includes full slot metadata for
;; automatic transient menu generation via `beads-defcommand'.
;;
;; Executes raw SQL queries against the beads database.
;;
;; Usage:
;;   (beads-execute 'beads-command-sql :query "SELECT * FROM issues")
;;   (beads-sql)  ; invoke transient menu

;;; Code:

(require 'beads-util)
(require 'beads-command)
(require 'beads-meta)
(require 'beads-option)

;;; SQL Command

;;;###autoload (autoload 'beads-sql "beads-command-sql" nil t)
(beads-defcommand beads-command-sql (beads-command-global-options)
  ((query
    :positional 1
    :type (or null string)
    :short-option "q"
    :argument "--query="
    :prompt "SQL query: "
    :group "SQL"
    :level 1
    :order 1
    :required t)
   (csv
    :type boolean
    :short-option "c"
    :group "Options"
    :level 2
    :order 2))
  :documentation "Execute raw SQL against the beads database.
Supports SELECT, INSERT, UPDATE, DELETE, and other SQL statements.")


;; Validate override removed: the base method checks :required slots
;; automatically via beads-command-validate-slots.

;; Note: Transient menu `beads-sql' is auto-generated by
;; `beads-defcommand' above (default :transient t behavior).
;; The transient docstring is extracted from the first sentence
;; of :documentation.

(provide 'beads-command-sql)
;;; beads-command-sql.el ends here
