;;; beads-command-branch.el --- Branch command class for beads -*- lexical-binding: t; -*-

;; Copyright (C) 2025

;; Author: Beads Contributors
;; Keywords: tools

;; This file is not part of GNU Emacs.

;;; Commentary:

;; This module defines the `beads-command-branch' EIEIO class for the
;; `bd branch' command.  Lists or creates Dolt branches in the beads
;; database.
;;
;; Without arguments: lists all branches.
;; With a name argument: creates a new branch.
;;
;; Usage:
;;   (beads-execute 'beads-command-branch)           ; list branches
;;   (beads-execute 'beads-command-branch :name "feature")  ; create branch
;;   (beads-branch)  ; invoke transient menu

;;; Code:

(require 'beads-util)
(require 'beads-command)
(require 'beads-meta)
(require 'beads-option)

;;; Branch Command

;;;###autoload (autoload 'beads-branch "beads-command-branch" nil t)
(beads-defcommand beads-command-branch (beads-command-global-options)
  ((name
    :positional 1
    :type (or null string)
    :short-option "n"
    :argument "--name="
    :prompt "Branch name (empty=list): "
    :group "Branch"
    :level 1
    :order 1))
  :documentation "List or create Dolt branches.
Without arguments, lists all branches.
With a name, creates a new branch.
Requires Dolt backend.")


;; Validate override removed: base handles slot-level validation.


;; Note: Transient menu `beads-branch' is auto-generated by
;; `beads-defcommand' above (default :transient t behavior).

(provide 'beads-command-branch)
;;; beads-command-branch.el ends here
