;;; beads-command-doctor.el --- Doctor command class for beads -*- lexical-binding: t; -*-

;; Copyright (C) 2025

;; Author: Beads Contributors
;; Keywords: tools

;; This file is not part of GNU Emacs.

;;; Commentary:

;; This module defines the `beads-command-doctor' EIEIO class for the
;; `bd doctor' command.  The class includes full slot metadata for
;; automatic transient menu generation via `beads-defcommand'.
;;
;; The bd doctor command performs sanity checks on the beads installation:
;; - Database version and migration status
;; - Schema compatibility
;; - Daemon health
;; - Circular dependencies
;; - Git hooks status
;; - And more...

;;; Code:

(require 'beads)
(require 'beads-command)
(require 'beads-meta)
(require 'beads-option)

;;; Doctor Command

;;;###autoload (autoload 'beads-doctor "beads-command-doctor" nil t)
(beads-defcommand beads-command-doctor (beads-command-global-options)
  ((path
    :positional 1)
   (check
    :type (or null string)
    :short-option "c"
    :prompt "Check (pollution): "
    :choices ("pollution")
    :group "Checks"
    :level 2
    :order 1)
   (check-health
    :type boolean
    :short-option "h"
    :group "Checks"
    :level 2
    :order 2)
   (deep
    :type boolean
    :short-option "d"
    :group "Checks"
    :level 2
    :order 3)
   (perf
    :type boolean
    :short-option "p"
    :group "Checks"
    :level 2
    :order 4)
   (fix
    :type boolean
    :short-option "f"
    :group "Fix Options"
    :level 3
    :order 1)
   (dry-run
    :type boolean
    :short-option "n"
    :group "Fix Options"
    :level 3
    :order 2)
   (yes
    :short-option "y"
    :type boolean
    :group "Fix Options"
    :level 3
    :order 3)
   (interactive-mode
    :long-option "interactive"
    :short-option "i"
    :type boolean
    :group "Fix Options"
    :level 3
    :order 4)
   (fix-child-parent
    :type boolean
    :short-option "C"
    :group "Fix Options"
    :level 4
    :order 5)
   (force
    :type boolean
    :short-option "F"
    :group "Fix Options"
    :level 4
    :order 6)
   (source
    :type (or null string)
    :short-option "s"
    :choices ("auto" "jsonl" "db")
    :group "Fix Options"
    :level 4
    :order 7)
   (output
    :short-option "o"
    :type (or null string)
    :prompt "Output file: "
    :group "Output"
    :level 3
    :order 1)
   (verbose
    :short-option "v"
    :type boolean
    :group "Output"
    :level 3
    :order 2)
   (clean
    :type boolean
    :short-option "D"
    :group "Checks"
    :level 4
    :order 5))
  :documentation "Represents bd doctor command.
Sanity checks the beads installation.
When executed with :json t, returns diagnostic results.")


;; Validate override removed: base handles slot-level validation.

;; Note: Transient menu `beads-doctor' is auto-generated by
;; `beads-defcommand' above (default :transient t behavior).
;; The transient docstring is extracted from the first sentence
;; of :documentation.

(provide 'beads-command-doctor)
;;; beads-command-doctor.el ends here
