;;; beads-command-admin.el --- Admin command classes for beads -*- lexical-binding: t; -*-

;; Copyright (C) 2025

;; Author: Beads Contributors
;; Keywords: tools

;; This file is not part of GNU Emacs.

;;; Commentary:

;; This module defines EIEIO command classes for `bd admin' operations.
;; Admin provides administrative commands for database maintenance.

;;; Code:

(require 'beads-command)
(require 'beads-option)
(require 'beads-reader)
(require 'transient)

;;; ============================================================
;;; Command Class: beads-command-admin-cleanup
;;; ============================================================

;; Transient `beads-admin-cleanup' is auto-generated by `beads-defcommand'.
;;;###autoload (autoload 'beads-admin-cleanup "beads-command-admin" nil t)
(beads-defcommand beads-command-admin-cleanup (beads-command-global-options)
  ((dry-run
    :type boolean
    :short-option "n"
    :group "Options"
    :level 1
    :order 1)
   (force
    :short-option "f"
    :type boolean
    :group "Options"
    :level 1
    :order 2)
   (cascade
    :type boolean
    :short-option "C"
    :group "Options"
    :level 1
    :order 3)
   (ephemeral
    :type boolean
    :short-option "e"
    :group "Filters"
    :level 1
    :order 1)
   (older-than
    :type (or null string integer)
    :short-option "o"
    :prompt "Days: "
    :group "Filters"
    :level 1
    :order 2))
  :documentation "Represents bd admin cleanup command.
Deletes closed issues and prunes expired tombstones.")


;;; ============================================================
;;; Command Class: beads-command-admin-compact
;;; ============================================================

;; Transient `beads-admin-compact' is auto-generated by `beads-defcommand'.
;;;###autoload (autoload 'beads-admin-compact "beads-command-admin" nil t)
(beads-defcommand beads-command-admin-compact (beads-command-global-options)
  ((dry-run
    :type boolean
    :short-option "n"
    :group "Options"
    :level 1
    :order 1)
   (analyze
    :type boolean
    :short-option "a"
    :group "Mode"
    :level 1
    :order 3)
   (apply
    :type boolean
    :short-option "A"
    :group "Mode"
    :level 1
    :order 4)
   (auto
    :type boolean
    :short-option "u"
    :group "Mode"
    :level 2
    :order 5)
   (stats
    :type boolean
    :short-option "s"
    :group "Mode"
    :level 1
    :order 6)
   (id
    :type (or null string)
    :short-option "i"
    :prompt "Issue ID: "
    :reader beads-reader-issue-id
    :group "Options"
    :level 1
    :order 2)
   (all
    :type boolean
    :short-option "l"
    :group "Options"
    :level 1
    :order 3)
   (force
    :type boolean
    :short-option "f"
    :group "Options"
    :level 2
    :order 4)
   (dolt
    :type boolean
    :short-option "d"
    :group "Mode"
    :level 1
    :order 7)
   (limit
    :type (or null string integer)
    :short-option "L"
    :group "Options"
    :level 2
    :order 6)
   (tier
    :type (or null string integer)
    :short-option "t"
    :prompt "Tier (1 or 2): "
    :group "Options"
    :level 2
    :order 7)
   (summary
    :type (or null string)
    :short-option "S"
    :prompt "Summary file: "
    :group "Options"
    :level 2
    :order 8)
   (batch-size
    :type (or null string integer)
    :short-option "b"
    :prompt "Batch size: "
    :group "Options"
    :level 3
    :order 9)
   (workers
    :type (or null string integer)
    :short-option "w"
    :group "Options"
    :level 3
    :order 10))
  :documentation "Represents bd admin compact command.
Compacts old closed issues to save space.")


;;; ============================================================
;;; Command Class: beads-command-admin-reset
;;; ============================================================

;; Transient `beads-admin-reset' is auto-generated by `beads-defcommand'.
;;;###autoload (autoload 'beads-admin-reset "beads-command-admin" nil t)
(beads-defcommand beads-command-admin-reset (beads-command-global-options)
  ((force
    :type boolean
    :short-option "f"
    :group "Options"
    :level 1
    :order 1))
  :documentation "Represents bd admin reset command.
Removes all beads data and configuration. DANGEROUS!")


;;; Parent Transient Menu

;;;###autoload (autoload 'beads-admin "beads-command-admin" nil t)
(transient-define-prefix beads-admin ()
  "Administrative commands for database maintenance.

Use with caution - prefer 'bd doctor --fix' for routine operations."
  ["Admin Commands"
   ("c" "Cleanup (delete closed)" beads-admin-cleanup)
   ("C" "Compact (save space)" beads-admin-compact)]
  ["Danger"
   ("R" "Reset (delete all)" beads-admin-reset)])

(provide 'beads-command-admin)
;;; beads-command-admin.el ends here
