;;; beads-command-defer.el --- Defer command classes for beads -*- lexical-binding: t; -*-

;; Copyright (C) 2025

;; Author: Beads Contributors
;; Keywords: tools

;; This file is not part of GNU Emacs.

;;; Commentary:

;; This module defines EIEIO command classes for `bd defer' and `bd undefer'.
;; Defer/undefer commands manage deferred status on issues.
;;
;; The class includes full slot metadata for automatic transient menu
;; generation via `beads-defcommand'.

;;; Code:

(require 'beads-command)
(require 'beads-meta)
(require 'beads-option)

;; Forward declarations
(declare-function beads-reader-issue-id "beads-reader")

;;; Defer Command

;;;###autoload (autoload 'beads-defer "beads-command-defer" nil t)
(beads-defcommand beads-command-defer (beads-command-global-options)
  ((issue-ids
    :positional-rest t
    :short-option "i"
    :argument "--id="
    :prompt "Issue ID(s): "
    :reader beads-reader-issue-id
    :group "Defer"
    :level 1
    :order 1
    :required t)
   (until
    :type (or null string)
    :short-option "u"
    :prompt "Until (e.g., +1h, tomorrow): "
    :group "Options"
    :level 1
    :order 1))
  :documentation "Represents bd defer command.
Defers one or more issues for later.")


;; Validate override removed: the base method checks :required slots
;; automatically via beads-command-validate-slots.


;;; Undefer Command

;;;###autoload (autoload 'beads-undefer "beads-command-defer" nil t)
(beads-defcommand beads-command-undefer (beads-command-global-options)
  ((issue-ids
    :positional-rest t
    :short-option "i"
    :argument "--id="
    :prompt "Issue ID(s): "
    :reader beads-reader-issue-id
    :group "Undefer"
    :level 1
    :order 1
    :required t))
  :documentation "Represents bd undefer command.
Undefers one or more issues (restores to open).")


;; Validate override removed: the base method checks :required slots
;; automatically via beads-command-validate-slots.

;; Note: Transient menus `beads-defer' and `beads-undefer' are
;; auto-generated by `beads-defcommand' above (default :transient t
;; behavior).

(provide 'beads-command-defer)
;;; beads-command-defer.el ends here
