;;; beads-audit.el --- CLI command-parity drift gate for beads.el -*- lexical-binding: t; -*-

;; Copyright (C) 2026

;; Author: Beads Contributors
;; Keywords: tools

;; This file is not part of GNU Emacs.

;;; Commentary:

;; This module audits beads.el's EIEIO command classes against the live
;; `bd' CLI surface and powers the command-parity drift gate exercised by
;; `lisp/test/beads-audit-test.el'.  It answers two questions:
;;
;;   1. Command presence -- does every addressable `bd' leaf command have a
;;      `beads-defcommand' class?  (`beads-audit-missing-commands')
;;   2. Slot fidelity -- does every CLI flag of a covered command have a
;;      matching slot?  (`beads-audit-slot-drift')
;;
;; The CLI surface is discovered by walking `bd <cmd> --help' recursively
;; (cobra's `Available Commands:' sections).  Help output never opens the
;; database, so the walk is fast and side-effect free -- unlike
;; `bd __complete', which triggers argument completion that reads the
;; store.  The class inventory is introspected live from EIEIO.
;;
;; What counts as a *real* gap is policy, and that policy lives as data in
;; `beads-meta' (the `beads-meta-parity-*' constants): router groups that
;; are classless by design, declared non-goal commands and flags, the
;; intentional `admin compact' multi-class cluster, and a baseline of known
;; accepted slot drift.  This module consumes those constants so the gate
;; and the documentation cannot drift apart
;; (see .designs/command-parity/analysis.md).
;;
;; The module is engine-agnostic: it only relies on `beads-meta' slot
;; introspection and the `beads-command-subcommand' resolver, so the same
;; harness can be pointed at a sibling command layer (e.g. gascity.el).

;;; Code:

(require 'cl-lib)
(require 'beads-custom)                 ; `beads-executable'
(require 'beads-meta)                   ; parity policy data + slot introspection
(require 'beads-command)                ; command classes + `beads-command-subcommand'

;;; ============================================================
;;; bd invocation (help only -- never touches the database)
;;; ============================================================

(defun beads-audit-bd-available-p ()
  "Return non-nil when the `bd' executable can be located and run."
  (and (stringp beads-executable)
       (executable-find beads-executable)
       t))

(defun beads-audit--path-segments (dotted)
  "Split DOTTED CLI path (e.g. \"migrate.schema\") into command words.
Returns a list like (\"migrate\" \"schema\"); nil for the root."
  (if (or (null dotted) (string-empty-p dotted))
      nil
    (split-string dotted "\\." t)))

(defvar beads-audit--help-cache (make-hash-table :test 'equal)
  "Process-lifetime memo of `bd ... --help' output, keyed by command path.
Help text is deterministic for a given `bd' build, so caching it for the
session keeps the audit fast (the walk and the drift pass otherwise
re-spawn `bd' for shared paths).  Call `beads-audit-clear-cache' after
upgrading `bd'.")

(defun beads-audit-clear-cache ()
  "Discard memoized `bd ... --help' output.  Call after upgrading `bd'."
  (interactive)
  (clrhash beads-audit--help-cache))

(defun beads-audit--help (segments)
  "Return `bd SEGMENTS --help' output as a string, or nil on failure.
SEGMENTS is a list of command words (nil for the root command).  Help
output is generated by cobra before any RunE hook, so it never opens
the beads store; `default-directory' is pinned to a neutral location to
keep the call free of working-directory side effects.  Results are
memoized in `beads-audit--help-cache'."
  (let* ((key (string-join (or segments (list "")) "\0"))
         (hit (gethash key beads-audit--help-cache 'miss)))
    (if (not (eq hit 'miss))
        hit
      (let ((out (with-temp-buffer
                   (let ((default-directory temporary-file-directory))
                     (ignore-errors
                       (apply #'process-file beads-executable nil t nil
                              (append segments '("--help"))))
                     (let ((s (buffer-string)))
                       (unless (string-empty-p s) s))))))
        (puthash key out beads-audit--help-cache)
        out))))

;;; ============================================================
;;; Command-tree discovery (via `--help' "Available Commands:")
;;; ============================================================

(defconst beads-audit--skip-commands '("help" "completion")
  "Top-level command names skipped during the CLI walk.
These are cobra shell/help plumbing, not beads commands.")

(defun beads-audit--command-line-names (text)
  "Collect command names from cobra command-listing TEXT.
Returns the first token of every two-space-indented `  name  summary'
entry line, excluding `beads-audit--skip-commands'.  Flag lines (which
begin with a dash) and section headers (no indent) do not match."
  (let (names)
    (dolist (line (split-string text "\n"))
      (when (string-match "\\`  \\([a-z][a-z0-9-]*\\)  +[^ ]" line)
        (let ((name (match-string 1 line)))
          (unless (member name beads-audit--skip-commands)
            (push name names)))))
    (nreverse (delete-dups names))))

(defun beads-audit--root-commands ()
  "Return the list of top-level `bd' command names.
The root `bd --help' lays its commands out in grouped sections rather
than a single `Available Commands:' block, so scan every command entry
that appears before the `Flags:' section."
  (let ((help (beads-audit--help nil)))
    (when help
      (let* ((flags-pos (string-match "^Flags:$" help))
             (region (if flags-pos (substring help 0 flags-pos) help)))
        (beads-audit--command-line-names region)))))

(defun beads-audit--child-commands (segments)
  "Return the immediate subcommand names of the command at SEGMENTS.
Parses the `Available Commands:' block of `bd SEGMENTS --help' (the
region between that header and the `Flags:' section).  Leaf commands
have no such block, so this returns nil for them."
  (let ((help (beads-audit--help segments)))
    (when help
      (let ((ac-pos (string-match "^Available Commands:$" help)))
        (when ac-pos
          (let* ((after (substring help (match-end 0)))
                 (flags-pos (string-match "^Flags:$" after))
                 (block (if flags-pos (substring after 0 flags-pos) after)))
            (beads-audit--command-line-names block)))))))

(defun beads-audit--walk (segments depth)
  "Return all dotted CLI paths strictly below SEGMENTS.
DEPTH guards against pathological recursion (cobra trees are shallow)."
  (let ((children (if segments
                      (beads-audit--child-commands segments)
                    (beads-audit--root-commands)))
        (acc nil))
    (dolist (child children)
      (let ((child-segs (append segments (list child))))
        (push (string-join child-segs ".") acc)
        (when (< depth 6)
          (setq acc (nconc acc (beads-audit--walk child-segs (1+ depth)))))))
    acc))

(defun beads-audit-cli-commands ()
  "Return all dotted CLI command paths discovered by walking `bd --help'.
The result includes both router-group paths (e.g. \"admin\") and leaf
paths (e.g. \"admin.compact\").  Requires `bd' to be available."
  (delete-dups (beads-audit--walk nil 0)))

;;; ============================================================
;;; Class inventory (live EIEIO introspection)
;;; ============================================================

(defun beads-audit--load-command-modules ()
  "Force-load every `beads-command-*.el' module so all classes are defined."
  (let* ((lib (or (locate-library "beads-command")
                  (locate-library "beads")))
         (dir (and lib (file-name-directory lib))))
    (when dir
      (dolist (file (directory-files dir nil "\\`beads-command-.+\\.elc?\\'"))
        (require (intern (file-name-sans-extension file)) nil t)))))

(defun beads-audit--all-command-classes ()
  "Return every concrete `beads-command' subclass as a list of symbols.
Force-loads all command modules first, then walks the EIEIO subclass
tree.  A class is concrete when it can be instantiated and resolves to a
non-nil CLI subcommand (abstract bases resolve to nil)."
  (beads-audit--load-command-modules)
  (let ((acc nil))
    (cl-labels ((walk (class)
                  (dolist (child (eieio--class-children (cl--find-class class)))
                    (push child acc)
                    (walk child))))
      (walk 'beads-command))
    (cl-remove-if-not
     (lambda (c)
       (ignore-errors (and (beads-command-subcommand (make-instance c)) t)))
     (delete-dups acc))))

(defun beads-audit-class-inventory ()
  "Return an alist of (CLI-PATH . CLASS-SYMBOLS) for all command classes.
CLI-PATH is dotted (e.g. \"migrate.schema\").  A path maps to more than
one class only for intentional multi-class clusters such as
`admin compact' (see `beads-meta-parity-intentional-collisions')."
  (let ((map nil))
    (dolist (class (beads-audit--all-command-classes))
      (let* ((sub (ignore-errors
                    (beads-command-subcommand (make-instance class))))
             (path (and sub (replace-regexp-in-string " " "." sub)))
             (cell (and path (assoc path map))))
        (when path
          (if cell
              (setcdr cell (cons class (cdr cell)))
            (push (cons path (list class)) map)))))
    (nreverse map)))

;;; ============================================================
;;; Flag introspection
;;; ============================================================

(defun beads-audit--global-flag-longs ()
  "Return CLI long-option names that beads.el handles globally.
These are the `beads-command-global-options' slot long-options plus the
pager toggle.  Every command inherits them, so they are excluded from
per-command slot-drift checks even when `bd' happens to list one under a
command's local `Flags:' section rather than `Global Flags:'."
  (let ((longs (list "no-pager"))
        (cobj (cl--find-class 'beads-command-global-options)))
    (when cobj
      (cl-loop for sd across (eieio--class-slots cobj)
               do (let ((l (alist-get :long-option (cl--slot-descriptor-props sd))))
                    (when l (push l longs)))))
    (delete-dups longs)))

(defun beads-audit--parse-flags-block (block)
  "Parse a cobra `Flags:'-style BLOCK string into a list of plists.
Each plist has :long, :short, :type and :description.  :type is
\"boolean\" when the flag takes no metavar, else the metavar string.
Continuation (wrapped description) lines are folded into the prior flag."
  (let (records)
    (dolist (line (split-string block "\n" t))
      (cond
       ((string-match
         (concat "^[ \t]+"
                 "\\(?:-\\([A-Za-z]\\), \\)?"        ; optional short
                 "--\\([A-Za-z0-9][A-Za-z0-9-]*\\)" ; long
                 "\\(?:[ \t]+\\([a-z][a-zA-Z0-9_]*\\(?:\\[\\][a-z]+\\)?\\)\\)?"
                 "[ \t][ \t]+\\(.*\\)$")
         line)
        (push (list :long (match-string 2 line)
                    :short (match-string 1 line)
                    :type (or (match-string 3 line) "boolean")
                    :description (or (match-string 4 line) ""))
              records))
       ((and records (string-match "^[ \t]\\{6,\\}\\(.*\\)$" line))
        (let ((last (car records)))
          (setf (plist-get last :description)
                (concat (plist-get last :description) " "
                        (string-trim (match-string 1 line))))
          (setcar records last)))))
    (nreverse records)))

(defun beads-audit--command-flag-longs (segments)
  "Return the local, non-global flag long-option names for a command.
Parses the `Flags:' block of `bd SEGMENTS --help', drops `--help' and
every globally-handled flag, and returns the remaining long-option
strings.  Returns nil when the command has no local flags."
  (let ((help (beads-audit--help segments)))
    (when help
      ;; Capture the local `Flags:' match end *before* the next
      ;; `string-match' clobbers the match data.
      (let* ((flags-pos (string-match "^Flags:\n" help))
             (flags-end (and flags-pos (match-end 0)))
             (gflags-pos (string-match "^Global Flags:" help))
             (block (when flags-end
                      (substring help flags-end
                                 (or gflags-pos (length help)))))
             (globals (beads-audit--global-flag-longs))
             longs)
        (when block
          (dolist (rec (beads-audit--parse-flags-block block))
            (let ((long (plist-get rec :long)))
              (when (and long
                         (not (string= long "help"))
                         (not (member long globals)))
                (push long longs)))))
        (nreverse (delete-dups longs))))))

(defun beads-audit--class-slot-longs (class)
  "Return the CLI long-option names declared by CLASS's non-positional slots.
Mirrors the long-option resolution used by the audit: the explicit
`:long-option' custom property, falling back to the slot name."
  (let (longs)
    (dolist (slot (beads-meta-command-slots class))
      (let* ((info (beads-meta-slot-info class slot))
             (props (plist-get info :custom-props))
             (positional (alist-get :positional props))
             (positional-rest (alist-get :positional-rest props))
             (long (or (alist-get :long-option props) (symbol-name slot))))
        (when (and long (not positional) (not positional-rest))
          (push long longs))))
    (delete-dups longs)))

;;; ============================================================
;;; Policy predicates (consume `beads-meta-parity-*' data)
;;; ============================================================

(defun beads-audit--intentional-collision-p (cli-path classes)
  "Return non-nil when (CLI-PATH . CLASSES) is a registered intentional collision.
CLASSES is the list of class symbols targeting CLI-PATH; it must match
the member set recorded in `beads-meta-parity-intentional-collisions'
exactly, so a drifted member set is still reported."
  (when-let ((entry (cdr (assoc cli-path beads-meta-parity-intentional-collisions))))
    (let ((expected (plist-get entry :classes)))
      (equal (sort (mapcar #'symbol-name (copy-sequence expected)) #'string<)
             (sort (mapcar #'symbol-name (copy-sequence classes)) #'string<)))))

(defun beads-audit--accepted-drift-p (cli-path long)
  "Return non-nil when missing flag LONG on CLI-PATH is policy-accepted.
True for declared non-goal flags (`beads-meta-parity-non-goal-flags')
and for the known accepted-drift baseline
\(`beads-meta-parity-accepted-drift')."
  (or (member long (cdr (assoc cli-path beads-meta-parity-non-goal-flags)))
      (member long (cdr (assoc cli-path beads-meta-parity-accepted-drift)))))

(defun beads-audit--missing-slots (cli-longs slot-longs cli-path)
  "Return the CLI-LONGS for CLI-PATH that are real, unaccepted slot gaps.
A long option is a gap when it is not present in SLOT-LONGS and not
policy-accepted for CLI-PATH (`beads-audit--accepted-drift-p').  This is
the pure core of the missing-slot check, factored out so it can be
exercised on synthetic input."
  (cl-remove-if (lambda (long)
                  (or (member long slot-longs)
                      (beads-audit--accepted-drift-p cli-path long)))
                cli-longs))

;;; ============================================================
;;; Findings
;;; ============================================================

(defun beads-audit-missing-commands (&optional cli-paths inventory)
  "Return addressable CLI command paths that have no `beads-defcommand' class.
Router groups (`beads-meta-parity-router-groups'), declared non-goal
commands (`beads-meta-parity-non-goal-commands'), and the recorded
category-1 backlog (`beads-meta-parity-planned-commands') are excluded
by policy.  CLI-PATHS and INVENTORY default to live discovery; pass
them to audit a synthetic surface (used by the gate's self-test)."
  (let* ((cli (or cli-paths (beads-audit-cli-commands)))
         (inv (or inventory (beads-audit-class-inventory)))
         (covered (mapcar #'car inv))
         (excluded (append beads-meta-parity-router-groups
                           beads-meta-parity-non-goal-commands
                           beads-meta-parity-planned-commands)))
    (cl-remove-if (lambda (p) (or (member p covered) (member p excluded)))
                  cli)))

(defun beads-audit-slot-drift (&optional inventory)
  "Return slot-drift findings beyond the accepted baseline.
Each finding is a plist (:path PATH :flag LONG :kind KIND), where KIND is

  `missing-slot'          a CLI flag with no matching slot, or
  `unexpected-collision'  several classes target one path without a
                          registered intent.

Globally-handled flags are ignored, the `admin compact' cluster's member
slots are unioned before diffing (see
`beads-meta-parity-intentional-collisions'), and flags listed in
`beads-meta-parity-non-goal-flags' / `beads-meta-parity-accepted-drift'
are treated as intentional.  INVENTORY defaults to live discovery; pass
it to audit a synthetic inventory (used by the gate's self-test)."
  (let ((inv (or inventory (beads-audit-class-inventory)))
        findings)
    (dolist (cell inv)
      (let* ((path (car cell))
             (classes (cdr cell))
             (segments (beads-audit--path-segments path)))
        (cond
         ((and (> (length classes) 1)
               (not (beads-audit--intentional-collision-p path classes)))
          (push (list :path path :flag nil :kind 'unexpected-collision)
                findings))
         (t
          (let* ((cli-longs (beads-audit--command-flag-longs segments))
                 (slot-longs (cl-remove-duplicates
                              (apply #'append
                                     (mapcar #'beads-audit--class-slot-longs
                                             classes))
                              :test #'equal)))
            (dolist (long (beads-audit--missing-slots cli-longs slot-longs path))
              (push (list :path path :flag long :kind 'missing-slot)
                    findings)))))))
    (nreverse findings)))

;;; ============================================================
;;; Classification (the CLI sync audit, REQ-001)
;;; ============================================================

(defun beads-audit-classify (&optional cli-paths inventory)
  "Classify every CLI command path into exactly one audit category.
CLI-PATHS and INVENTORY default to live discovery; pass them to audit
a synthetic surface (used by the self-test).

Returns a list of plists, one per path, sorted by path:

  (:path   PATH
   :category CAT        one of the symbols `covered', `router',
                        `out-of-scope', `missing', `collision'
   :disposition STRING  human-readable disposition sentence
   :rationale STRING    per-command decision, or the empty string when
                        the path has no recorded rationale)

Categories map onto the CLI sync audit's buckets:

- `covered'      a class exists and no unaccepted slot drift -- no action.
- `router'       a router group, transient parent without a class (policy).
- `out-of-scope' deliberately skipped (category 3), recorded in
                 `beads-meta-parity-non-goal-commands'.
- `missing'      category 1: core user-facing command with no class; the
                 backlog for later sync-plan phases.
- `collision'    category 2-adjacent: several classes target one path
                 without a registered intent (a drift-gate finding).

Category 2 (an existing class missing 1.3.x flags) is intentionally NOT
a classification here: a classified command is still `covered' as a
command, and its flag gaps are the slot-drift findings returned by
`beads-audit-slot-drift'.  The report joins the two so each covered
command with gaps is labeled category 2 in the audit output."
  (let* ((cli (or cli-paths (beads-audit-cli-commands)))
         (inv (or inventory (beads-audit-class-inventory)))
         (covered (mapcar #'car inv))
         (drift (beads-audit-slot-drift inv))
         (collisions (cl-remove-if (lambda (d) (eq (plist-get d :kind)
                                                   'missing-slot))
                                   drift))
         (drift-paths (mapcar (lambda (d) (plist-get d :path)) drift))
         entries)
    (dolist (path cli)
      (let* ((classes (cdr (assoc path inv)))
             (rationale (or (cdr (assoc path
                                  beads-meta-parity-command-rationales))
                            ""))
             category disposition)
        (cond
         ((and (> (length classes) 1)
               (cl-find path collisions
                        :test (lambda (p d)
                                (equal p (plist-get d :path)))))
          ;; Several classes target one path without a registered intent:
          ;; surfaced as its own category so it cannot hide as "covered".
          (setq category 'collision
                disposition
                "Category 2-adjacent drift finding: several classes target\nthis path without a registered intent in\n`beads-meta-parity-intentional-collisions'."))
         ((member path covered)
          (if (member path drift-paths)
              (setq category 'covered
                    disposition
                    (format "Category 2: covered by %s, but carries\nunaccepted slot drift (see the slot-drift gate)."
                            (mapconcat #'symbol-name classes ", ")))
            (setq category 'covered
                  disposition
                  (format "Covered by %s; no unaccepted slot drift."
                          (mapconcat #'symbol-name classes ", ")))))
         ((member path beads-meta-parity-router-groups)
          (setq category 'router
                disposition
                "Category N/A: router group surfaced as a parent transient\nmenu without a class (project policy)."))
         ((member path beads-meta-parity-non-goal-commands)
          (setq category 'out-of-scope
                disposition
                (or rationale
                    "Category 3: deliberately out of scope (no rationale\nrecorded -- add one to `beads-meta-parity-command-rationales').")))
         ((member path beads-meta-parity-planned-commands)
          (setq category 'missing
                disposition
                (or (and (not (string-empty-p rationale)) rationale)
                    "Category 1: core user-facing command with no class\nyet; recorded in the sync-plan backlog.")))
         (t
          (setq category 'missing
                disposition
                (if (string-empty-p rationale)
                    "Category 1: core user-facing command with no class."
                  rationale))))
        (push (list :path path :category category
                    :disposition disposition :rationale rationale)
              entries)))
    (sort entries
          (lambda (a b)
            (string< (plist-get a :path)
                     (plist-get b :path))))))

(defun beads-audit-classification-summary (classification)
  "Return a plist of counts keyed by category from CLASSIFICATION.
Keys: `:total' `:covered' `:router' `:out-of-scope' `:missing' and
`:collision'.  Category 2 (flag gaps) is counted separately from the
slot-drift findings, not from CLASSIFICATION."
  (let ((total 0) (covered 0) (router 0) (out-of-scope 0)
        (missing 0) (collision 0))
    (dolist (entry classification)
      (cl-incf total)
      (cl-case (plist-get entry :category)
        (covered (cl-incf covered))
        (router (cl-incf router))
        (out-of-scope (cl-incf out-of-scope))
        (missing (cl-incf missing))
        (collision (cl-incf collision))))
    (list :total total :covered covered :router router
          :out-of-scope out-of-scope :missing missing
          :collision collision)))

;;; ============================================================
;;; Report rendering (interactive + batch)
;;; ============================================================

(defun beads-audit-report-string (&optional cli-paths inventory)
  "Return the full command-parity report as a string.
CLI-PATHS and INVENTORY default to live discovery.  The same text is
displayed by `beads-audit-report' and written by
`beads-audit-report-to-file', so the interactive view, the batch export,
and the recorded audit artifact cannot disagree."
  (let* ((cli (or cli-paths (beads-audit-cli-commands)))
         (inv (or inventory (beads-audit-class-inventory)))
         (classification (beads-audit-classify cli inv))
         (counts (beads-audit-classification-summary classification))
         (drift (beads-audit-slot-drift inv))
         (missing-slot-count
          (cl-count-if (lambda (d) (eq (plist-get d :kind) 'missing-slot))
                       drift))
         (lines nil))
    (cl-labels ((emit (fmt &rest args)
                  (push (apply #'format fmt args) lines)))
      (emit "beads.el command-parity report")
      (emit "==============================")
      (emit "")
      (emit "CLI command paths discovered:   %d" (plist-get counts :total))
      (emit "Command classes (unique paths): %d" (length inv))
      (emit "")
      (emit "Classification (every path in exactly one category):")
      (emit "  Covered (category 1/2 resolved, class exists):  %d"
            (plist-get counts :covered))
      (emit "  Router groups (parent transient, no class):     %d"
            (plist-get counts :router))
      (emit "  Out-of-scope skips (category 3):                %d"
            (plist-get counts :out-of-scope))
      (emit "  Missing core commands (category 1 backlog):     %d"
            (plist-get counts :missing))
      (emit "  Unexpected collisions (drift-gate finding):     %d"
            (plist-get counts :collision))
      (emit "  Slot-drift findings (category 2 flag gaps):     %d"
            missing-slot-count)
      (emit "")
      (emit "Category 1 -- core user-facing commands with no class (backlog):")
      (let ((n 0))
        (dolist (entry classification)
          (when (eq (plist-get entry :category) 'missing)
            (cl-incf n)
            (emit "  - %s" (plist-get entry :path))
            (dolist (l (split-string (plist-get entry :disposition) "\n"))
              (emit "      %s" l))))
        (when (= n 0)
          (emit "  (none -- every core command has a class)")))
      (emit "")
      (emit "Category 2 -- existing classes missing 1.3.x flags:")
      (let ((n 0))
        (dolist (d drift)
          (when (eq (plist-get d :kind) 'missing-slot)
            (cl-incf n)
            (emit "  - %s --%s" (plist-get d :path) (plist-get d :flag))))
        (when (= n 0)
          (emit "  (none -- no unaccepted slot drift)")))
      (emit "")
      (emit "Category 3 -- deliberately out-of-scope commands (skip decisions):")
      (let ((n 0))
        (dolist (entry classification)
          (when (eq (plist-get entry :category) 'out-of-scope)
            (cl-incf n)
            (emit "  - %s" (plist-get entry :path))
            (dolist (l (split-string (plist-get entry :disposition) "\n"))
              (emit "      %s" l))))
        (when (= n 0)
          (emit "  (none)")))
      (emit "")
      (emit "Router groups (parent transients, no class -- policy):")
      (dolist (entry classification)
        (when (eq (plist-get entry :category) 'router)
          (emit "  - %s" (plist-get entry :path))))
      (emit "")
      (emit "Borderline calls recorded by the 1.3.x audit:")
      (let ((n 0))
        (dolist (entry classification)
          (when (and (eq (plist-get entry :category) 'covered)
                     (not (string-empty-p (plist-get entry :rationale))))
            (cl-incf n)
            (emit "  - %s" (plist-get entry :path))
            (dolist (l (split-string (plist-get entry :rationale) "\n"))
              (emit "      %s" l))))
        (when (= n 0)
          (emit "  (none recorded)")))
      (emit "")
      (emit "Unexpected multi-class collisions:")
      (let ((n 0))
        (dolist (d drift)
          (when (eq (plist-get d :kind) 'unexpected-collision)
            (cl-incf n)
            (emit "  - %s" (plist-get d :path))))
        (when (= n 0)
          (emit "  (none)")))
      (string-join (nreverse lines) "\n"))))

;;;###autoload
(defun beads-audit-report-to-file (path)
  "Write the command-parity report to file PATH (batch audit export).
Uses the live `bd' walk; identical text to `beads-audit-report'.
Returns PATH."
  (interactive "FWrite parity report to: ")
  (unless (beads-audit-bd-available-p)
    (user-error "The `bd' executable is not available"))
  (beads-audit-clear-cache)
  (let ((report (beads-audit-report-string)))
    (with-temp-file path
      (insert report)
      (insert "\n")))
  path)

;;; ============================================================
;;; Interactive report
;;; ============================================================

;;;###autoload
(defun beads-audit-report ()
  "Display the human-readable command-parity report.
Walks the live `bd' CLI surface, introspects the class inventory, and
renders the classified inventory produced by `beads-audit-classify':
every command in exactly one category with its disposition, plus the
slot-drift findings beyond the accepted baseline.  The identical text is
available for batch export via `beads-audit-report-string' and
`beads-audit-report-to-file'."
  (interactive)
  (unless (beads-audit-bd-available-p)
    (user-error "The `bd' executable is not available"))
  (beads-audit-clear-cache)             ; fresh data for an interactive run
  (let ((report (beads-audit-report-string)))
    (with-current-buffer (get-buffer-create "*beads-parity*")
      (let ((inhibit-read-only t))
        (erase-buffer)
        (insert report)
        (goto-char (point-min))
        (special-mode)))
    (display-buffer "*beads-parity*")))

(provide 'beads-audit)
;;; beads-audit.el ends here
