;;; beads-command-reopen.el --- Reopen command class for beads -*- lexical-binding: t; -*-

;; Copyright (C) 2025

;; Author: Beads Contributors
;; Keywords: tools

;; This file is not part of GNU Emacs.

;;; Commentary:

;; This module defines the `beads-command-reopen' EIEIO class for the
;; `bd reopen' command.  The class includes full slot metadata for
;; automatic transient menu generation via `beads-defcommand'.
;;
;; The bd reopen command reopens closed issues by setting their status
;; to 'open' and clearing the closed_at timestamp.  This is more explicit
;; than 'bd update --status open' and emits a Reopened event.
;;
;; Features:
;; - Reopen single or multiple issues at once
;; - Optional reason field for documentation
;; - Invalidates completion cache after reopening
;;
;; Usage:
;;   (beads-command-execute (beads-command-reopen :issue-ids '("bd-1")
;;                                                 :reason "Needs more work"))
;;   (beads-execute 'beads-command-reopen)  ; convenience function

;;; Code:

(require 'beads-command)
(require 'beads-meta)
(require 'beads-option)
(require 'beads-types)

;; Forward declarations
(declare-function beads--invalidate-completion-cache "beads-util")
(declare-function beads-reader-reopen-issue-id "beads-reader")
(defvar beads-auto-refresh)

;;; Reopen Command

;;;###autoload (autoload 'beads-reopen "beads-command-reopen" nil t)
(beads-defcommand beads-command-reopen (beads-command-global-options)
  ((issue-ids
    :positional 1
    :type (list-of string)
    :separator " "
    :short-option "i"
    :transient transient-option
    :argument "--id="
    :prompt "Issue ID: "
    :reader beads-reader-reopen-issue-id
    :group "Reopen Issue"
    :level 1
    :order 1
    :required t)
   (reason
    :type (or null string)
    :short-option "r"
    :transient beads-transient-multiline
    :documentation "Reason for reopening"
    :group "Reopen Issue"
    :level 1
    :order 2))
  :documentation "Represents bd reopen command.
Reopens one or more closed issues with optional reason.
When executed with :json t, returns beads-issue instance (or list
of instances when multiple IDs provided)."
  :result (list-of beads-issue))


;; Validate override removed: the base method checks :required slots
;; automatically via beads-command-validate-slots.

;; Parse override removed: the base method handles JSON-to-domain
;; parsing automatically via :result (list-of beads-issue).
;; The execute-interactive method normalizes results to a list.

(cl-defmethod beads-command-execute-interactive ((cmd beads-command-reopen))
  "Execute CMD to reopen issue and show result."
  (oset cmd json t)
  (let* ((result (beads-command-execute cmd))
         (issues (if (listp result) result (list result))))
    (beads--invalidate-completion-cache)
    (if issues
        (message "Reopened %d issue%s: %s"
                 (length issues)
                 (if (= (length issues) 1) "" "s")
                 (mapconcat (lambda (i) (oref i id)) issues ", "))
      (message "No issues reopened"))))

;; Note: Transient menu `beads-reopen' is auto-generated by
;; `beads-defcommand' above (default :transient t behavior).

(provide 'beads-command-reopen)
;;; beads-command-reopen.el ends here
