;;; beads-command-diff.el --- Diff command class for beads -*- lexical-binding: t; -*-

;; Copyright (C) 2025

;; Author: Beads Contributors
;; Keywords: tools

;; This file is not part of GNU Emacs.

;;; Commentary:

;; This module defines the `beads-command-diff' EIEIO class for the
;; `bd diff' command.  Shows differences between two commits or branches
;; in the Dolt-backed beads database.
;;
;; Usage:
;;   (beads-execute 'beads-command-diff :from-ref "HEAD~1" :to-ref "HEAD")
;;   (beads-diff)  ; invoke transient menu

;;; Code:

(require 'beads-util)
(require 'beads-command)
(require 'beads-meta)
(require 'beads-option)

;;; Diff Command

;;;###autoload (autoload 'beads-diff "beads-command-diff" nil t)
(beads-defcommand beads-command-diff (beads-command-global-options)
  ((from-ref
    :positional 1
    :type (or null string)
    :short-option "f"
    :argument "--from="
    :prompt "From ref: "
    :group "Diff"
    :level 1
    :order 1
    :required t)
   (to-ref
    :positional 2
    :type (or null string)
    :short-option "t"
    :argument "--to="
    :prompt "To ref: "
    :group "Diff"
    :level 1
    :order 2
    :required t))
  :documentation "Show differences between two commits or branches.
Requires Dolt backend.")


;; Validate override removed: the base method checks :required slots
;; automatically via beads-command-validate-slots.

;; Note: Transient menu `beads-diff' is auto-generated by
;; `beads-defcommand' above (default :transient t behavior).

(provide 'beads-command-diff)
;;; beads-command-diff.el ends here
