;;; beads-command-comments.el --- Comments command classes for beads -*- lexical-binding: t; -*-

;; Copyright (C) 2025

;; Author: Beads Contributors
;; Keywords: tools

;; This file is not part of GNU Emacs.

;;; Commentary:

;; This module defines EIEIO command classes for `bd comments' operations.
;; Comments allows viewing and adding comments on issues.  The class
;; includes full slot metadata for automatic transient menu generation
;; via `beads-defcommand'.
;;
;; bd comments - List all comments on an issue
;; bd comments add - Add a comment to an issue
;;
;; Usage:
;;   (beads-execute 'beads-command-comments :issue-id "bd-1")           ; List comments
;;   (beads-execute 'beads-command-comments-add :issue-id "bd-1"
;;                                :text "Comment text")  ; Add comment

;;; Code:

(require 'beads-command)
(require 'beads-meta)
(require 'beads-option)
(require 'beads-types)

;; Forward declarations
(declare-function beads--invalidate-completion-cache "beads-util")
(declare-function beads-reader-issue-id "beads-reader")
(defvar beads-auto-refresh)

;;; Comments Command

;; Transient menu `beads-comments' is auto-generated by `beads-defcommand'.

;;;###autoload (autoload 'beads-comments "beads-command-comments" nil t)
(beads-defcommand beads-command-comments (beads-command-global-options)
  ((issue-id
    :positional 1
    :type (or null string)
    :short-option "i"
    :argument "--issue-id="
    :prompt "Issue ID: "
    :reader beads-reader-issue-id
    :group "List Comments"
    :level 1
    :order 1
    :required t))
  :documentation "Represents bd comments command.
Lists all comments on an issue."
  :result (list-of beads-comment))


;;; Comments Add Command

;; Transient menu `beads-comments-add' is auto-generated by `beads-defcommand'.

;;;###autoload (autoload 'beads-comments-add "beads-command-comments" nil t)
(beads-defcommand beads-command-comments-add (beads-command-global-options)
  ((issue-id
    :positional 1
    :type (or null string)
    :short-option "i"
    :argument "--issue-id="
    :prompt "Issue ID: "
    :reader beads-reader-issue-id
    :group "Add Comment"
    :level 1
    :order 1
    :required t)
   (text
    :positional 2
    :type (or null string)
    :short-option "t"
    :transient beads-transient-multiline
    :argument "--text="
    :documentation "Comment"
    :group "Add Comment"
    :level 1
    :order 2)
   (file
    :short-option "f"
    :type (or null string)
    :prompt "File path: "
    :group "Add Comment"
    :level 2
    :order 3)
   (author
    :short-option "a"
    :type (or null string)
    :group "Add Comment"
    :level 2
    :order 4))
  :documentation "Represents bd comments add command.
Adds a comment to an issue.")


(cl-defmethod beads-command-validate ((command beads-command-comments-add))
  "Validate comments add COMMAND.  Requires issue-id and text or file."
  (with-slots (issue-id text file) command
    (cond
     ((not issue-id) "Issue ID is required")
     ((string-empty-p issue-id) "Issue ID cannot be empty")
     ((and (or (not text) (string-empty-p text))
           (or (not file) (string-empty-p file)))
      "Comment text or file is required")
     (t nil))))

(cl-defmethod beads-command-execute-interactive
    ((cmd beads-command-comments-add))
  "Execute CMD in compilation buffer with human-readable output."
  (oset cmd json nil)
  ;; Invalidate cache since comment may affect issue display
  (beads--invalidate-completion-cache)
  (cl-call-next-method))

;;; Parent Transient Menu

;;;###autoload (autoload 'beads-comments-menu "beads-command-comments" nil t)
(transient-define-prefix beads-comments-menu ()
  "Manage issue comments.

Comments allow adding notes, updates, and discussions to issues.
Each comment includes a timestamp and optional author attribution."
  ["Comments Commands"
   ("l" "List comments" beads-comments)
   ("a" "Add comment" beads-comments-add)]
  ["Quick Actions"
   ("q" "Quit" transient-quit-one)])

(provide 'beads-command-comments)
;;; beads-command-comments.el ends here
