;;; beads-command-ping.el --- Ping command class for beads -*- lexical-binding: t; -*-

;; Copyright (C) 2026

;; Author: Beads Contributors
;; Keywords: tools

;; This file is not part of GNU Emacs.

;;; Commentary:

;; This module defines the `beads-command-ping' EIEIO class for the
;; `bd ping' command.  The class includes full slot metadata for
;; automatic transient menu generation via `beads-defcommand'.
;;
;; The bd ping command is a lightweight health check that confirms bd
;; can reach its database.  Steps:
;;   1. Resolve the .beads workspace
;;   2. Open the store (embedded or server)
;;   3. Run a trivial query (issue count)
;;   4. Report timing
;;
;; Exit 0 on success, exit 1 on failure.  No subcommand-specific flags
;; beyond the global options (--json for structured output).
;;
;; Usage:
;;   (beads-execute 'beads-command-ping)
;;   (beads-execute 'beads-command-ping :json t)

;;; Code:

(require 'beads-command)
(require 'beads-meta)
(require 'beads-option)
(require 'transient)

;;; Ping Command

;;;###autoload (autoload 'beads-ping "beads-command-ping" nil t)
(beads-defcommand beads-command-ping (beads-command-global-options)
  ()
  :documentation "Represents bd ping command.
Lightweight health check that confirms bd can reach its database.
Exits 0 on success, 1 on failure.")

;; Note: Transient menu `beads-ping' is auto-generated by
;; `beads-defcommand' above (default :transient t behavior).

(provide 'beads-command-ping)
;;; beads-command-ping.el ends here
