;;; beads-command-migrate.el --- Migrate command classes for beads -*- lexical-binding: t; -*-

;; Copyright (C) 2025

;; Author: Beads Contributors
;; Keywords: tools

;; This file is not part of GNU Emacs.

;;; Commentary:

;; This module defines EIEIO command classes for `bd migrate' operations.
;; Migrate provides database migration and data transformation commands.
;; Transient menus are auto-generated by `beads-defcommand'.

;;; Code:

(require 'beads-command)
(require 'beads-option)
(require 'transient)

;;; Migrate Command

;;;###autoload (autoload 'beads-migrate "beads-command-migrate" nil t)
(beads-defcommand beads-command-migrate (beads-command-global-options)
  ((dry-run
    :type boolean
    :short-option "n"
    :group "Options"
    :level 1
    :order 1)
   (cleanup
    :type boolean
    :short-option "c"
    :group "Options"
    :level 1
    :order 2)
   (yes
    :short-option "y"
    :type boolean
    :group "Options"
    :level 1
    :order 3)
   (inspect
    :type boolean
    :short-option "i"
    :group "Options"
    :level 2
    :order 4)
   (update-repo-id
    :type boolean
    :short-option "u"
    :group "Options"
    :level 2
    :order 5))
  :documentation "Detect and migrate database schema to current version.")

;;; Migrate Issues Command

;;;###autoload (autoload 'beads-migrate-issues "beads-command-migrate" nil t)
(beads-defcommand beads-command-migrate-issues (beads-command-global-options)
  ((source
    :positional 1)
   (target
    :positional 2))
  :documentation "Move issues between repositories.")

;;; Migrate Sync Command

;;;###autoload (autoload 'beads-migrate-sync "beads-command-migrate" nil t)
(beads-defcommand beads-command-migrate-sync (beads-command-global-options)
  ()
  :documentation "Migrate to sync.branch workflow for multi-clone setups.")

;;; Migrate Hooks Command

;;;###autoload (autoload 'beads-migrate-hooks "beads-command-migrate" nil t)
(beads-defcommand beads-command-migrate-hooks (beads-command-global-options)
  ((dry-run
    :type boolean
    :short-option "n"
    :group "Options"
    :level 1
    :order 1)
   (apply
    :type boolean
    :short-option "a"
    :group "Options"
    :level 1
    :order 2)
   (yes
    :type boolean
    :short-option "y"
    :group "Options"
    :level 1
    :order 3))
  :documentation "Migrate git hooks to marker-managed format."
  :cli-command "migrate hooks")

;;; Parent Transient Menu

;;;###autoload (autoload 'beads-migrate-menu "beads-command-migrate" nil t)
(transient-define-prefix beads-migrate-menu ()
  "Database migration commands."
  ["Migrate Commands"
   ("m" "Auto-migrate" beads-migrate)
   ("H" "Hooks" beads-migrate-hooks)
   ("i" "Move issues" beads-migrate-issues)
   ("s" "Sync workflow" beads-migrate-sync)])

(provide 'beads-command-migrate)
;;; beads-command-migrate.el ends here
