;;; beads-command-batch.el --- Batch command class for beads -*- lexical-binding: t; -*-

;; Copyright (C) 2025

;; Author: Beads Contributors
;; Keywords: tools

;; This file is not part of GNU Emacs.

;;; Commentary:

;; This module defines the `beads-command-batch' EIEIO class for the
;; `bd batch' command.  The class includes full slot metadata for
;; automatic transient menu generation via `beads-defcommand'.
;;
;; The bd batch command runs multiple write operations in a single
;; database transaction.  Commands are read from stdin (one per line)
;; or from a file via -f/--file.  All operations execute inside a
;; single dolt transaction: on any error the whole batch is rolled
;; back, otherwise it is committed with one DOLT_COMMIT.
;;
;; Supported grammar (one command per line):
;;   close <id> [reason...]
;;   update <id> <key>=<value> [<key>=<value> ...]
;;   create <type> <priority> <title...>
;;   dep add <from-id> <to-id> [type]
;;   dep remove <from-id> <to-id>
;;
;; Usage:
;;   (beads-execute 'beads-command-batch :file "ops.txt")

;;; Code:

(require 'beads-command)
(require 'beads-meta)
(require 'beads-option)
(require 'transient)

;;; Batch Command

;;;###autoload (autoload 'beads-batch "beads-command-batch" nil t)
(beads-defcommand beads-command-batch (beads-command-global-options)
  ((dry-run
    :type boolean
    :group "Options"
    :level 1
    :order 1
    :documentation "Parse input and echo commands without executing")
   (file
    :type (or null string)
    :short-option "f"
    :prompt "Commands file: "
    :group "Options"
    :level 1
    :order 2
    :documentation "Read commands from file instead of stdin")
   (message
    :type (or null string)
    :short-option "m"
    :prompt "DOLT_COMMIT message: "
    :group "Options"
    :level 1
    :order 3
    :documentation "DOLT_COMMIT message (default: 'bd: batch N ops by <actor>')"))
  :documentation "Represents bd batch command.
Runs multiple write operations in a single database transaction.
Commands are read from stdin or from a file via -f/--file.")

;; Note: Transient menu `beads-batch' is auto-generated by
;; `beads-defcommand' above (default :transient t behavior).

(provide 'beads-command-batch)
;;; beads-command-batch.el ends here
