;;; beads-command-history.el --- History command class for beads -*- lexical-binding: t; -*-

;; Copyright (C) 2025

;; Author: Beads Contributors
;; Keywords: tools

;; This file is not part of GNU Emacs.

;;; Commentary:

;; This module defines the `beads-command-history' EIEIO class for the
;; `bd history' command.  Shows version history for an issue in the
;; Dolt-backed beads database.
;;
;; Usage:
;;   (beads-execute 'beads-command-history :issue-id "bd-42")
;;   (beads-history)  ; invoke transient menu

;;; Code:

(require 'beads)
(require 'beads-command)
(require 'beads-meta)
(require 'beads-option)

;;; History Command

;;;###autoload (autoload 'beads-history "beads-command-history" nil t)
(beads-defcommand beads-command-history (beads-command-global-options)
  ((issue-id
    :positional 1
    :type (or null string)
    :short-option "i"
    :argument "--id="
    :prompt "Issue ID: "
    :reader beads-reader-close-issue-id
    :group "History"
    :level 1
    :order 1
    :required t)
   (limit
    :type (or null string integer)
    :short-option "l"
    :prompt "Limit (0=all): "
    :group "Options"
    :level 2
    :order 2))
  :documentation "Show version history for an issue.
Requires Dolt backend.")


;; Validate override removed: the base method checks :required slots
;; automatically via beads-command-validate-slots.

;; Note: Transient menu `beads-history' is auto-generated by
;; `beads-defcommand' above (default :transient t behavior).

(provide 'beads-command-history)
;;; beads-command-history.el ends here
