;;; beads-command-merge-slot.el --- Merge-slot command classes for beads -*- lexical-binding: t; -*-

;; Copyright (C) 2025

;; Author: Beads Contributors
;; Keywords: tools

;; This file is not part of GNU Emacs.

;;; Commentary:

;; This module defines EIEIO command classes for `bd merge-slot' operations.
;; Merge-slot gates serialize conflict resolution in the merge queue,
;; preventing multiple agents from racing to resolve conflicts.
;;
;; A merge slot is an exclusive access primitive: only one agent can hold
;; it at a time.  The slot uses:
;;   - status=open:        slot is available
;;   - status=in_progress: slot is held
;;   - metadata.holder:    who currently holds the slot
;;   - metadata.waiters:   priority-ordered queue of waiters
;;
;; Each command class uses `beads-defcommand' with default :transient t,
;; which auto-generates the transient menu from slot metadata.
;;
;; Usage:
;;   (beads-execute 'beads-command-merge-slot-create)    ; create the slot bead
;;   (beads-execute 'beads-command-merge-slot-check)     ; check availability
;;   (beads-execute 'beads-command-merge-slot-acquire :holder "furiosa" :wait t)
;;   (beads-execute 'beads-command-merge-slot-release :holder "furiosa")

;;; Code:

(require 'beads-command)
(require 'beads-option)
(require 'transient)

;;; ============================================================
;;; Command Class: beads-command-merge-slot-create
;;; ============================================================

;;;###autoload (autoload 'beads-merge-slot-create "beads-command-merge-slot" nil t)
(beads-defcommand beads-command-merge-slot-create (beads-command-global-options)
  ()
  :documentation "Create a merge slot bead for serialized conflict resolution.
The slot ID is generated automatically from the beads prefix."
  :cli-command "merge-slot create")

;; Note: Transient menu `beads-merge-slot-create' is auto-generated by
;; `beads-defcommand' above (default :transient t behavior).

;;; ============================================================
;;; Command Class: beads-command-merge-slot-check
;;; ============================================================

;;;###autoload (autoload 'beads-merge-slot-check "beads-command-merge-slot" nil t)
(beads-defcommand beads-command-merge-slot-check (beads-command-global-options)
  ()
  :documentation "Check if the merge slot is available or held.
Returns: available, held by <holder>, or not found."
  :cli-command "merge-slot check")

;; Note: Transient menu `beads-merge-slot-check' is auto-generated by
;; `beads-defcommand' above (default :transient t behavior).

;;; ============================================================
;;; Command Class: beads-command-merge-slot-acquire
;;; ============================================================

;;;###autoload (autoload 'beads-merge-slot-acquire "beads-command-merge-slot" nil t)
(beads-defcommand beads-command-merge-slot-acquire (beads-command-global-options)
  ((holder
    :type (or null string)
    :short-option "h"
    :prompt "Holder (default: BEADS_ACTOR): "
    :group "Options"
    :level 1
    :order 1)
   (wait
    :type boolean
    :short-option "w"
    :group "Options"
    :level 1
    :order 2))
  :documentation "Acquire the merge slot for exclusive access.
If slot is available, acquires it.  If held and --wait is set,
adds to the waiters queue."
  :cli-command "merge-slot acquire")

;; Note: Transient menu `beads-merge-slot-acquire' is auto-generated by
;; `beads-defcommand' above (default :transient t behavior).

;;; ============================================================
;;; Command Class: beads-command-merge-slot-release
;;; ============================================================

;;;###autoload (autoload 'beads-merge-slot-release "beads-command-merge-slot" nil t)
(beads-defcommand beads-command-merge-slot-release (beads-command-global-options)
  ((holder
    :type (or null string)
    :short-option "h"
    :prompt "Holder (for verification): "
    :group "Options"
    :level 1
    :order 1))
  :documentation "Release the merge slot after conflict resolution is complete.
Sets status back to open and clears the holder field."
  :cli-command "merge-slot release")

;; Note: Transient menu `beads-merge-slot-release' is auto-generated by
;; `beads-defcommand' above (default :transient t behavior).

;;; Parent Transient Menu

;;;###autoload (autoload 'beads-merge-slot "beads-command-merge-slot" nil t)
(transient-define-prefix beads-merge-slot ()
  "Merge-slot gate management for serialized conflict resolution.

Merge slots prevent monkey knife fights: only one agent can hold
the slot at a time, preventing cascading conflict storms."
  ["Merge Slot Commands"
   ("c" "Create slot" beads-merge-slot-create)
   ("k" "Check status" beads-merge-slot-check)
   ("a" "Acquire slot" beads-merge-slot-acquire)
   ("r" "Release slot" beads-merge-slot-release)])

(provide 'beads-command-merge-slot)
;;; beads-command-merge-slot.el ends here
