name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        emacs_version:
          - '27.1'
          - '27.2'
          - '28.2'
          - '29.1'
          - 'snapshot'

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Emacs ${{ matrix.emacs_version }}
        uses: purcell/setup-emacs@master
        with:
          version: ${{ matrix.emacs_version }}

      - name: Cache Eldev dependencies
        uses: actions/cache@v3
        with:
          path: ~/.emacs.d/eldev
          key: ${{ runner.os }}-eldev-${{ hashFiles('Eldev') }}
          restore-keys: |
            ${{ runner.os }}-eldev-

      - name: Install Eldev
        run: curl -fsSL https://raw.github.com/doublep/eldev/master/webinstall/github-eldev | sh

      - name: Install Beads
        run: curl -fsSL https://raw.githubusercontent.com/steveyegge/beads/main/install.sh | bash

      - name: Run tests
        run: eldev -p -dtT test

      - name: Byte-compile
        run: eldev -p -dtT compile

      - name: Lint
        if: matrix.emacs_version != 'snapshot'
        run: eldev -p -dtT lint
